<?php

function company_page_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'company_page/company_page';
}

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry' and 'drush cc router'.
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */

function company_page_theme($existing, $type, $theme, $path){

  return [

    'company_form' => [
      'variables' => ['name_of_user' => NULL,'grmds_url' => NULL,'website' => NULL,'industry' => NULL,'company_size' => NULL,'company_type' => NULL,'headquarters' => NULL,'founded' => NULL,'page_picture' => NULL,'tagline' => NULL,],
    ],
    'user_page' => [
      'variables' => ['logged_in_user_id' => NULL,'uid' => NULL,'name_of_user' => NULL,'grmds_url' => NULL,'website' => NULL,'industry' => NULL,'company_size' => NULL,'company_type' => NULL,'headquarters' => NULL,'founded' => NULL,'page_picture' => NULL,'tagline' => NULL, 'postresultarray' => [], 'about' => NULL, 'count_following' => NULL, 'count_following_each_other' => NULL, 'post_id' => NULL, 'poster_id' => NULL, 'poster_count'=> NULL, 'poster_company_name' => NULL, 'poster_image' => NULL, 'poster_message' => NULL, 'posted_time' => NULL, 'allresults' => [],],
    ],
    'error_no_user_page' => [
      'variables' => ['name_of_user' => NULL,],
    ],
    'user_edit_page' => [
      'variables' => ['uid' => NULL,'name_of_user' => NULL,'grmds_url' => NULL,'website' => NULL,'industry' => NULL,'company_size' => NULL,'company_type' => NULL,'headquarters' => NULL,'founded' => NULL,'page_picture' => NULL,'tagline' => NULL,],

    ],
    'admin_tools' => [
      'variables' => ['test_variable' => NULL,],

    ],

  ];

}


